import math from "math.n";

string input = console.in("Put a number");
input = input.toNumber();
if(typeOf(input) === "number"){
    console.out(math.abs(input));
}


------

TOKENS

------

IMPORT IDENTIFIER FROM STRINGV SEMI

STRING IDENTIFIER EQUAL IDENTIFIER POINT IDENTIFIER PAR_OPEN STRINGV PAR_CLOSE SEMI
IDENTIFIER EQUAL IDENTIFIER POINT IDENTIFIER PAR_OPEN PAR_CLOSE SEMI
IF PAR_OPEN IDENTIFIER PAR_OPEN IDENTIFIER PAR_CLOSE IS_EQUIVALENT STRINGV PAR_CLOSE CURLY_OPEN
    IDENTIFIER POINT IDENTIFIER PAR_OPEN IDENTIFIER POINT IDENTIFIER PAR_OPEN IDENTIFIER PAR_CLOSE PAR_CLOSE SEMI
CURLY_CLOSE